### ISSUE TITLE
PMenu for actions

### ISSUE THREAD

**Issue by lewis6991** [lewis6991/gitsigns.nvim#100]
Easier way to discover actions as opposed to using mappings.

- hunk stage
- hunk reset
- hunk preview
- line blame

**Comment by oberblastmeister** [comment]
what about using telescope to discover actions

**Comment by lewis6991** [comment]
How do you mean? Using `lsp_code_actions`? For that Telescope uses `vim.lsp.buf_request_sync(0, "textDocument/codeAction",...)` to get code actions which gitsigns can't really hook into since vim.lsp requires lsp's to work over rpc.

**Comment by oberblastmeister** [comment]
No not using lsp. Just using a `static_finder` for example and then just execute the command that the user picked. `lsp_code_actions` also uses `static_finder`

**Comment by lewis6991** [comment]
Ah I see.

I've also been thinking about doing something that integrates with https://github.com/kosayoda/nvim-lightbulb which also uses `vim.lsp.buf_request`. It's a shame the current lsp stuff doesn't allow in-process lsp's.

Maybe we can just redefine `vim.lsp.buf_request` and make it call the original so we can insert more actions, that way it will work for telescope code actions too.

**Comment by oberblastmeister** [comment]
Yeah in process lsps would be very cool however I think they would be pretty slow because libuv threads don't really work currently and also don't expose the vim object in the new lua state. Tj actually did something for lua lsps in neovim here https://github.com/tjdevries/tree-sitter-lua/tree/master/lua/nlsp. What do you mean by redefining `buf_request`?

**Comment by lewis6991** [comment]
> Yeah in process lsps would be very cool however I think they would be pretty slow because libuv threads ...

Would you even need to use threads for simple a lsp. For gitsigns I'd like to just provide some of the capabilities but just do it on the main thread, e.g. provide code actions, hover, etc. It would also allow us to implement something like https://github.com/iamcco/diagnostic-languageserver completely in lua.

> What do you mean by redefining buf_request?

```
local orig_buf_request = vim.lsp.buf_request
vim.lsp.buf_request = function(..., cb)
  local new_cb = function()
     -- do stuff
 end
  orig_buf_request(..., new_cb)
end
```
Basically just as a means to hook into the functions and inject extra logic.

**Comment by oberblastmeister** [comment]
yeah since you are just overriding capabilities and stuff obviously you wouldn't need new thread. Redefining buf_request seems like a bad idea as that is a core function and other people would want to use it so they wouldn't want something unexpected to happen. There definately needs to be a way to define more capabilities though in lua

**Comment by lewis6991** [comment]
> Redefining buf_request seems like a bad idea as that is a core function and other people would want to use it so they wouldn't want something unexpected to happen.

I agree. If I do that, it will be a opt-in proof-of-concept kind of feature with disclaimers in the docs. It's mostly just for fun.

**Comment by mjlbach** [comment]
This is way off topic, but people have asked for the ability to "inject" additional handlers to mock an out of process language server in order to use an in-process handler (see: https://github.com/neovim/neovim/issues/14258). I'm generally opposed to this (idk what TJ's thoughts are), as I think the point of the LSP implementation/framework is for communicating with language servers, and this desire seems like it's more driven out of how nice the interface is around language servers rather than the API being a good solution for the underlying problem (I don't think indirecting a formatter via EFM for example is really a cleaner solution than using something via formatter.nvim). I'd rather invest time in exposing/generalizing the diagnostic API, or allowing plugin authors to compose the `vim.lsp.buf` series of helper functions with their own custom functions instead of trying to make additional ways to override/hook into the lsp infrastructure in core.

**Comment by lewis6991** [comment]
https://github.com/jose-elias-alvarez/null-ls.nvim provides a gitsigns builtin extension for code actions that meets the goal of this issue.
