### ISSUE TITLE
(Un)stage file command

### ISSUE THREAD

**Issue by tomaskallup** [lewis6991/gitsigns.nvim#127]
**Is your feature request related to a problem? Please describe.**
Sometimes I need to stage or unstage an entire file with multiple changes, it would be nice to have a command for this, so I can just bind this. I tried a custom bind with just `!git add %` but that takes my focus away as it prints the stdout and exit code.

**Describe the solution you'd like**
New exposed functions from the gitsigns module: `stage_file` and `unstage_file`, which would run `git add` and `git reset HEAD` respectively on the current buffer.

**Describe alternatives you've considered**
- Bind to just run `!git add %` - it's an ugly solution as it prints info on success & isn't async.
- Custom lua function to use some of the gitsigns internals & plenary, but I couldn't get it working properly

I would love to try and implement this in gitsigns, I just want feedback, if it's a desired feature.

**Comment by lewis6991** [comment]
This should be really easy to implement. Just need to add a function in `gitsigns.tl` called `stage_file` which will be similar to `stage_hunk`. In there you'll need to call the git command via `await`. The `add` git function already exists since we need it to add files for files with conflicts (`await(git.add_file(bcache.toplevel, bcache.relpath))`). You will need to modify `git.add_file` to remove the `--intent-to-add` flag.
