### ISSUE TITLE
Inline blame is completely obscured if cursorline is turned on

### ISSUE THREAD

**Issue by goronfreeman** [lewis6991/gitsigns.nvim#255]
**Is your feature request related to a problem? Please describe.**
The inline blame is completely invisible if `cursorline` is turned on, since the color of the blame text and the color of the cursorline are the same. I'm assuming that this is not an issue with all colorschemes, but I would imagine it would be an issue with many.

**Describe the solution you'd like**
A config option to change the color of the text or providing a default that is less likely to be obscured would both work.

**Additional context**
I am using Neovim 0.5 with [this](https://github.com/shaunsingh/nord.nvim) fork of the nord theme that has support for treesitter.

**Comment by lewis6991** [comment]
I tried a selection of colorschemes and only nord had this issue:
  - [lewis6991/github_dark.vim](https://github.com/lewis6991/github_dark.vim)
  - [lewis6991/moonlight.vim](https://github.com/lewis6991/moonlight.vim)
  - [joshdick/onedark.vim](https://github.com/joshdick/onedark.vim)
  - [folke/tokyonight.nvim](https://github.com/folke/tokyonight.nvim)
  - [shaunsingh/nord.nvim](https://github.com/shaunsingh/nord.nvim)
  - [chriskempson/base16-vim](https://github.com/chriskempson/base16-vim)

> A config option to change the color of the text

You can already customize this since the current_line_blame has its own highlight `GitSignsCurrentLineBlame`, you just need to define it. Something like `highlight link GitSignsCurrentLineBlame Visual` will work. You may want to raise a PR for nord to fix this.

**Comment by lougreenwood** [comment]
As a note, I also have this issue with Dracula

**Comment by marcelarie** [comment]
> As a note, I also have this issue with Dracula, using `highlight link GitSignsCurrentLineBlame Visual` fixed it 👍

For anyone that wants to set this with lua:
```lua
vim.api.nvim_set_hl(
  0,
  "GitSignsCurrentLineBlame",
  { link = "Visual" }
)
```
