### ISSUE TITLE
Sign column is modified during insert mode

### ISSUE THREAD

**Issue by jebaum** [lewis6991/gitsigns.nvim#273]
**Describe the bug**
When typing in insert mode in a modified + tracked file, occasionally the sign column briefly disappears then reappears. If you have the sign column configured to only be displayed if there's currently any signs, as opposed to always on, this causes the whole buffer to shift left and right in a jarring way. It seems more likely to happen if you're typing quickly.

I'm guessing this is due to gitsigns running in the background, and possibly wiping out the current signs a fraction of a second before receiving updated ones from however git is being called. If this is the case, I think it'd be nicer to display the new set of signs before wiping out the old set to avoid the shifting back and forth behavior. Otherwise, maybe just don't try to update signs while in insert mode?

**To Reproduce**

init.vim:

```vim
let $PLUGIN_DIRECTORY = '~/.config/nvim/bundle'
set runtimepath^=$PLUGIN_DIRECTORY/plenary.nvim
set runtimepath^=$PLUGIN_DIRECTORY/gitsigns.nvim

lua << EOF
require('gitsigns').setup {
  debug_mode = true, -- You must add this to enable debug messages
  -- config
}
EOF
```

1. Open any tracked text file in a git repo
2. Go into insert mode and start quickly typing

**Observed output**
Sign column will occasionally disappear entirely and then reappear, causing whole buffer to shift left and right by the width of the sign column

**Screenshots**
I hope my description was pretty clear, I can fairly reliably reproduce this every ~10 seconds or so when typing fast and take a screen recording if that would be helpful.

**Additional context**
System: Arch Linux, gitsigns version 67ba1f1, plenary version 8bae2c1
Neovim version: v0.6.0-dev+59-g2475161de

**Comment by lewis6991** [comment]
This is probably due to your system being slow... sorry.

> I'm guessing this is due to gitsigns running in the background, and possibly wiping out the current signs a fraction of a second before receiving updated ones from however git is being called. If this is the case, I think it'd be nicer to display the new set of signs before wiping out the old set to avoid the shifting back and forth behavior. Otherwise, maybe just don't try to update signs while in insert mode?

This is almost true. The signs are cleared immediately before applying new ones. See https://github.com/lewis6991/gitsigns.nvim/blob/d0fea19f72c9584a82786a9532edbb5e2efb53f7/teal/gitsigns/manager.tl#L70

There is very little running in between signs being cleared and reapplied and not many people have reported this issue.

I'm not really sure what we can do about this.  Clearing the signs after won't be easy and probably won't work as we'd need to store the signs we need to remove. And instead of seeing signs removed and added, you would just see signs being added then removed.

I think the last person that reported this was also an arch user so it could be a problem with that platform. Is your hardware recent?

**Comment by jebaum** [comment]
Doubt it's my system being slow - just rebuilt my machine last month with a 5950x, 32GB 3600mhz DDR4, and I originally noticed this editing a file on an nvme ssd.

Looking at the code though, yeah not sure what could reasonably be done. Maybe neovim needs an API to allow pausing of redrawing certain portions of the UI while certain bits of code run. The only other solution I can think of would be to expose some kind of `require"gitsigns".pause_signcolumn_updates()` and `require"gitsigns".start_signcolumn_updates()` functions that can be called in `InsertEnter` and `InsertLeave` autocmds, but you're the judge of whether that's a good idea or not / how much work it would be.

**Comment by lewis6991** [comment]
Hmm, instead of clearing all signs, we could inspect the signs present and make a more informed choice on how to apply new signs.

Also do you have `lazyredraw` set?

**Comment by jebaum** [comment]
I'm sure that would work, but I'd be hesitant to even request adding too much complication to the codebase for an issue almost nobody is experiencing. If `start` and `pause` functions are simple to implement, they at least wouldn't add more logic to frequently exercised code paths.

I usually have `nolazyredraw` set, I switched to `lazyredraw` and was also able to reproduce, which is what I expected - I think that setting only applies to buffer updates while macros are running.

**Comment by lewis6991** [comment]
> I'm sure that would work, but I'd be hesitant to even request adding too much complication to the codebase for an issue almost nobody is experiencing. If start and pause functions are simple to implement, they at least wouldn't add more logic to frequently exercised code paths.

It would add complexity, but less than you would expect. We can keep this issue open and I'll draft a PR to see what such a solution could look like. The signs API is kind of bad IMO (and its implementation in C is even worse), so we already do quite a few tricks to overcome its problems.

The `start` and `stop`  functions would actually be quite tricky to implement. Currently gitsigns runs an update on every buffer change.

> I usually have nolazyredraw set, I switched to lazyredraw and was also able to reproduce, which is what I expected - I think that setting only applies to buffer updates while macros are running.

Yeah I thought as much, was worth a stab. I suspect this is a platform issue since not many people have reported this and it seems your instance is redrawing the screen much more.

One other potential reason for this is that another plugin might be causing this. I've noticed other plugins invoke excessive screen redraws ([example](https://github.com/romgrk/nvim-treesitter-context/pull/21)). 

One other thing. Have you tried altering `config.update_debounce`. If you increase this you should see less sign column glitchyness.

**Comment by lewis6991** [comment]
Can you give #276 a go.

I found another way to aleviate this problem by not updating the signs if the resulting signs don't change which we can quickly figure out by comparing the heads of the hunks. This could end up being quite an efficiency boost for buffers with lots of signs as hunks are like compressed signs.

**Comment by jebaum** [comment]
Was not able to reproduce after pulling down #276 locally!

**Comment by minhduc0711** [comment]
#276 also resolves this issue for me.

**Comment by Iron-E** [comment]
#276 also fixes it for me!
