### ISSUE TITLE
Show status message when trying to navigate to a hunk in a file with no hunks

### ISSUE THREAD

**Issue by mroavi** [lewis6991/gitsigns.nvim#293]
Showing status messages when navigating hunks was recently implemented in #240. I recently noticed that there is a difference between this implementation and the default vim navigation functionality (e.g. navigating the quick fix list). The difference is that if you try to navigate an unpopulated quick fix list, an error/warning message is shown. On the other hand, when trying to navigate hunks in a file with no hunks, no message is printed. Would it be possible to add this feature so as to be more in line with default vim navigation behavior? It's also quite reassuring to see this message. A related question is: should an error/warning message be shown when trying to navigate hunks in a file that is not inside a git repo? @zapling your thoughts on this?

**Comment by lewis6991** [comment]
> Would it be possible to add this feature so as to be more in line with default vim navigation behavior? 

Sounds like a good idea. PR's are very welcome if you want to take a stab at it, otherwise I'll get round to this.

> A related question is: should an error/warning message be shown when trying to navigate hunks in a file that is not inside a git repo?

If a file isn't trackable by a git repo, then gitsigns won't attach and hence the mappings won't get set up. If you try to run the gitsigns functions/commands directly then it won't do anything but I guess some sort of error message would be better.
