### ISSUE TITLE
Flickering cursor

### ISSUE THREAD

**Issue by vatosarmat** [lewis6991/gitsigns.nvim#305]
My cursor is flickering when I'm typing text in insert mode. Is it possible no to draw signs when inserting text and do it only when leaving insert mode or saving the buffer?

**Comment by lewis6991** [comment]
Are you sure it is gitsigns causing the flickering?

If the hunk headers don't change during insert mode, then the signs aren't redrawn because they will be the same, so the flickering is probably due to something else.

Have you also tried increasing `config.update_debounce`, the default is pretty short.

**Comment by vatosarmat** [comment]
Indeed, that was my statusline having read `@+` in one of its expressions and spawning `/usr/bin/xsel -o -b` per each key stroke.
Sorry for bothering you with this and thank you very mach for the great plugin

**Comment by mkujbus** [comment]
I experience the same, can you help me how you resolved the issue?

**Comment by lewis6991** [comment]
Firstly, are you sure the flickering is caused by gitsigns? Please determine this first.

**Comment by vatosarmat** [comment]
@mkujbus obviously I've changed problematic expression, that was my self-made status line. This shows that cursor flickering occurs when neovim has performance bottleneck somewhere
