### ISSUE TITLE
[Question] Why this plugin dependents on plenary?

### ISSUE THREAD

**Issue by kevinhwang91** [lewis6991/gitsigns.nvim#34]
https://github.com/lewis6991/gitsigns.nvim/blob/6433129ce42257e20e6518a0c73ee7636b5a8b3d/lua/gitsigns.lua#L1-L4

It seems that [plenary](https://github.com/nvim-lua/plenary.nvim) is overkill for gitsigns.nvim.

**Comment by lewis6991** [comment]
Plenary is just a library of lua functions, it's mostly used for `plenary/job` which is a critical dependency of the plugin. The other stuff is used pretty much because it is available and convenient. `plenary/path` also contains some useful stuff but it is a little under-developed at the moment so I do some of its functions manually.

Lua itself is simple and has a very lean standard library, nvim extends that a bit (see `:help lua`), but there are still many standard things that aren't included in which `plenary.nvim` fills the gap. I don't really see it as overkill, it simply saves me time having to duplicate lots of functions it has already implemented and tested.

**Comment by kevinhwang91** [comment]
Thanks for your explanation. I hope some convenient functions of `plenary` should be merged into nvim `runtime` as an official support.

In my option, `plenary` is unlike a library, it's just a patch.
