### ISSUE TITLE
Gitsigns disappear upon save (regression)

### ISSUE THREAD

**Issue by m-lima** [lewis6991/gitsigns.nvim#521]
### Description

First of all, thanks for this great plugin! When moving from old-style vim config and using git-gutter, this plugin really showed how much more refined the modern nvim lua plugins can be. So, again, thank you :)

I unfortunately stumbled into a regression. The gutter icons will disappear when the buffer is saved.
I have a strong feeling that this is related to the autocmd for formatting the buffer when saving.

This wasn't a problem before, but a recent commit surfaced this issue.
Last time this behaved correctly was on ac5ba87898dda3893610ed4023f40c4493f4a07f
Regression happened on a680c32388d0fac307d97320090721ece2280917

It took me a while to get the minimal config working (it requires lsp to be installed, so it was a bit of a hassle), but it should showcase the issue now.

### Neovim version

0.6.1

### Operating system and version

macOS Monterey 12.2

### Expected behavior

Gitsigns "gutter" symbols should not disappear upon save

### Actual behavior

It disappears when the buffer is saved. It will then reappear when changes are made to the bufffer.
See attached video:

https://user-images.githubusercontent.com/13945557/163169595-585b283e-3ce7-4088-a3ef-44a3aae0d8b6.mov

### Minimal config

```Lua
vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  lspconfig = 'https://github.com/neovim/nvim-lspconfig',
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/' .. name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

require('gitsigns').setup {
  debug_mode = true, -- You must add this to enable debug messages
}

-- You'll need to have sumneko_lua installed for this example specifically
-- But the point is that we need any LSP in order to have the `vim.lsp.buf.formatting_sync()` autocomd
require('lspconfig').sumneko_lua.setup({})
vim.cmd([[autocmd BufWritePost <buffer> silent! lua vim.lsp.buf.formatting_sync()]])
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. :e <file_with_unstaged_changes>
3. :w

**Comment by m-lima** [comment]
This seems to be related to `autocmd BufWritePre lua.vim.lsp.buf.formatting_sync()` or `autocmd BufWritePost lua.vim.lsp.buf.formatting_sync()`

**Comment by lewis6991** [comment]
Thanks for the bug report, I am able to reproduce.

**Comment by lewis6991** [comment]
Ah this is really annoying! The only reason it worked before was because the speculative signs (which were removed in https://github.com/lewis6991/gitsigns.nvim/commit/ac5ba87898dda3893610ed4023f40c4493f4a07f) were causing extra updates to happen which was masking this issue.

`vim.lsp.buf.formatting_sync()` causes the whole buffer to be rewritten, it effectively removes all lines then adds new ones. Due to the way in which signs work, this causes them to be removed despite the fact `sign_unplace` doesn't get called.

A potential fix is quite simple. We just need to make this block unconditional: https://github.com/lewis6991/gitsigns.nvim/blob/f2e9e30c3e95ccc05ff5b4984e5a07f264198f45/teal/gitsigns/manager.tl#L224-L230

But this might cause some flickering for some users.

I'll think about this some more.

**Comment by lewis6991** [comment]
@m-lima can you try #523?

**Comment by m-lima** [comment]
> @m-lima can you try #523?

Checked it out. It works 👍 And just as you predicted, there's a little flicker.

I have my formatting in a `BufWritePre` with a sync command. And this seems to be the recommended way to do it.
Now, a question coming from someone that's obviously not used to this codebase 😄 Would it make sense for gitsigns to hook on `BufWritePost` ?

**Comment by lewis6991** [comment]
Autocmds are the wrong way to look at this. Gitsigns uses `nvim_buf_attach` which calls a callback whenever the buffer is changed, therefore it is already updating after `vim.lsp.buf.formatting_sync`. 

The issue is that Gitsigns has an optimization where it won't redraw the signs if the diff didn't change, and apparently this optimisation reduces flickering for some users.

This is what happens:
- Gitsigns runs, applies the signs
- `vim.lsp.buf.formatting_sync` runs and removes all the signs
- Gitsigns runs again (due to `vim.lsp.buf.formatting_sync`), but because the diffs haven't changed, signs aren't redrawn.

The PR basically just forces a sign redraw if a sign was removed by `vim.lsp.buf.formatting_sync`.

**Comment by lewis6991** [comment]
Can you try #523 again? The first version had some mistakes, despite appearing to fix the issue at hand.

**Comment by lewis6991** [comment]
For reference, I was able to reduce this much further so LSP isn't needed:

```lua
vim.o.packpath = '/tmp/nvim/site'

vim.opt.runtimepath:append('/Users/lewis/projects/gitsigns.nvim')

require('gitsigns').setup {
  debug_mode = true, -- You must add this to enable debug messages
}

local function get_line(bufnr, row)
  return (vim.api.nvim_buf_get_lines(bufnr, row, row + 1, false))[1]
end

SYNC = function()
  local bufnr = vim.api.nvim_get_current_buf()
  local max = vim.api.nvim_buf_line_count(bufnr)
  local end_col = #(get_line(bufnr, max - 1))
  local text = vim.api.nvim_buf_get_lines(bufnr, 0, -1, false)
  text[#text+1] = ''
  vim.api.nvim_buf_set_text(bufnr, 0, 0, max-1, end_col, text)
  vim.api.nvim_buf_set_lines(bufnr, -2, -1, true, {})
end

vim.cmd([[autocmd BufWritePost <buffer> silent! lua vim.schedule(SYNC)]])
```
