### ISSUE TITLE
A way to fuzzy search over gitsigns commands

### ISSUE THREAD

**Issue by ldelossa** [lewis6991/gitsigns.nvim#594]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to fuzzy search over gitsigns commands.

There is a nice completion function used for "Gitsigns" user commands, but you can't access these in a fuzzy searcher like fzf-lua or telescope. 

Likewise, gitsigns only exports a single command, so you can't access gitsigns commands via a more general "UserCommands" search function that fzf-lua and telescope provide.

**Describe the solution you'd like**
Use a vim.ui.select over the commands which gitsigns makes available, let fzf-lua and telescope override this and allow users to fuzzy search over gitsigns commands.

**Describe alternatives you've considered**
Export a user command for each gitsigns command available, and simply let fzf-lua and telescope search over exported user commands.

**Comment by lewis6991** [comment]
Is you use nvim-cmp, the completion menu will show all the gitsigns commands:

<img width="835" alt="image" src="https://user-images.githubusercontent.com/7904185/179771028-83c2b8d2-5b51-469a-9d87-771a5d38bb68.png">

Gitsigns implements completion of subcommands, it is upto third-party plugins like telescope on whether they want to invoke this completion.

Otherwise you can look at the docs of gitsigns.

**Comment by ldelossa** [comment]
> Gitsigns implements completion of subcommands

what do you mean by this?

**Comment by lewis6991** [comment]
See `:help command-completion`.

**Comment by ldelossa** [comment]
ah, i'm aware of those. but none of this precludes not relying on nvim-cmp and just placing the commands in a ui selection, right?

**Comment by ldelossa** [comment]
Thanks a ton, this is a big help.
