### ISSUE TITLE
Allow repeating movements with ; and ,

### ISSUE THREAD

**Issue by augustocdias** [lewis6991/gitsigns.nvim#794]
When we call `next_hunk` or `prev_hunk` it would be nice if it were possible to repeat them with `;` and `,`.

I don't know how complex is this, specially when other plugins like [treesitter-textobjects can overwrite them as well](https://github.com/nvim-treesitter/nvim-treesitter-textobjects#text-objects-move)

**Comment by ghostbuster91** [comment]
The approach where each plugin redefines `;` and `,` is not a viable long term strategy. The best would be to have these motions integrate-able in the nvim core but that seems to be quite complex and there are others more pressing issues. 

Because of that I created a [small plugin](https://github.com/ghostbuster91/nvim-next) that other plugins can hook into. I even made an integration for git-signs as I use them on daily basis.

**Comment by lewis6991** [comment]
I agree.

I'll close this as out-of-scope but will consider a PR if anyone want to try to implement this.
