### ISSUE TITLE
Gitsigns don't see vim.env change anymore

### ISSUE THREAD

**Issue by coffebar** [lewis6991/gitsigns.nvim#895]
### Description

I'm using `vim.env.GIT_DIR` and `vim.env.GIT_DIR` to tell Neovim where is my git bare repo for dotfiles.
More about this and the code snippet [here](https://github.com/coffebar/neovim-project#how-to-manage-dotfiles-repo).

Since commit [19654d9](https://github.com/lewis6991/gitsigns.nvim/commit/19654d963e4f1d6d6543f38ab9802092393508c2) it stopped working with Gitsigns, only works with Fugitive. 
From this commit and later I can't see any git signs, can't navigate via hunks, etc. when I'm using bare git repo.
I printed `vim.env.GIT_DIR` from command mode and saw that the value is correct. 
The problem is related to a specific commit.

### Neovim version

v0.9.2

### Operating system and version

Arch Linux

### Expected behavior

git repo detected by `vim.env.GIT_DIR` and `vim.env.GIT_DIR`

### Actual behavior

git repo not detected 

### Minimal config

```Lua
It's not easy to do, but I will make it later if required...
```

### Steps to reproduce

```lua
-- set these variables, cd to home and open some changed git-tracked file
vim.env.GIT_DIR = git_dir
vim.env.GIT_WORK_TREE = home
```

**Comment by lewis6991** [comment]
@coffebar can you try #896

**Comment by coffebar** [comment]
works great, thanks!

**Comment by lewis6991** [comment]
Just to note this fix won't be required in Nvim 0.10.

**Comment by guibou** [comment]
Hello.

I'm just having issues with gitsigns since a few days. I do not really understand what happened, it could be a bump of nvim (I'm using the nightly git version), or a bump of gitsign, or i don't really know.

However I've tracked this to:

```
  -- Fix #895. Only needed for Nvim 0.9 and older
  spec.clear_env = true
```

Turning that to `false` fix the problem.

In short, the problem is that nvim fails with:

```
vim.schedule callback: ...unwrapped-nightly/share/nvim/runtime/lua/vim/_system.lua:249: ENOENT: no such file or directory                                                                       
stack traceback:                                                                                                                                                                                
        [thread: 0x7fde2c7f7ef0] [C]: in function 'asystem'                                                                                                                                     
        [thread: 0x7fde2c7f7ef0] ...aume/.vim/plugged/gitsigns.nvim/lua/gitsigns/git/cmd.lua:58: in function 'git_command'                                                                      
        [thread: 0x7fde2c7f7ef0] ...ume/.vim/plugged/gitsigns.nvim/lua/gitsigns/git/repo.lua:213: in function 'get_info'                                                                        
        [thread: 0x7fde2c7f7ef0] ...ume/.vim/plugged/gitsigns.nvim/lua/gitsigns/git/repo.lua:126: in function 'get'                                                                             
        [thread: 0x7fde2c7f7ef0] ...uillaume/.vim/plugged/gitsigns.nvim/lua/gitsigns/git.lua:243: in function 'new'                                                                             
        [thread: 0x7fde2c7f7ef0] ...laume/.vim/plugged/gitsigns.nvim/lua/gitsigns/attach.lua:217: in function 'fn'                                                                              
        [thread: 0x7fde2c7f7ef0] ...ume/.vim/plugged/gitsigns.nvim/lua/gitsigns/debounce.lua:78: in function 'attach_throttled'                                                                 
        [thread: 0x7fde2c7f7ef0] ...laume/.vim/plugged/gitsigns.nvim/lua/gitsigns/attach.lua:363: in function <...laume/.vim/plugged/gitsigns.nvim/lua/gitsigns/attach.lua:362>                 
stack traceback:                                                                                                                                                                                
        [C]: in function 'error'                                                                                                                                                                
        ...llaume/.vim/plugged/gitsigns.nvim/lua/gitsigns/async.lua:229: in function '_finish'                                                                                                  
        ...llaume/.vim/plugged/gitsigns.nvim/lua/gitsigns/async.lua:322: in function '_resume'                                                                                                  
        ...llaume/.vim/plugged/gitsigns.nvim/lua/gitsigns/async.lua:317: in function <...llaume/.vim/plugged/gitsigns.nvim/lua/gitsigns/async.lua:307>    
```

Each time I'm open a new file with `gitsigns`, and of course, gitsigns in not working at all.

I've traced the different system call and found that it is looking for `git` in:

```
163309 execve("/run/current-system/sw/bin/git", ["git", "--no-pager", "--no-optional-locks", "--literal-pathspecs", "-c", "gc.auto=0", "rev-parse", "--show-toplevel", "--absolute-git-dir", "--abbrev-ref", "HEAD"], 0x273d5ef0 /* 0 vars */) = -1 ENOENT (No such file or directory)
163309 execve("/bin/git", ["git", "--no-pager", "--no-optional-locks", "--literal-pathspecs", "-c", "gc.auto=0", "rev-parse", "--show-toplevel", "--absolute-git-dir", "--abbrev-ref", "HEAD"], 0x273d5ef0 /* 0 vars */) = -1 ENOENT (No such file or directory)
163309 execve("/usr/bin/git", ["git", "--no-pager", "--no-optional-locks", "--literal-pathspecs", "-c", "gc.auto=0", "rev-parse", "--show-toplevel", "--absolute-git-dir", "--abbrev-ref", "HEAD"], 0x273d5ef0 /* 0 vars */) = -1 ENOENT (No such file or directory)
```

so it looks like it tries to look for `git` in `/usr/bin` and in `/bin` and in `/run/current-system/sw/bin/git`. Amazingly, none of these path but `/run/current-system/sw/bin/` are in my `PATH` and `git` is inside none of these path.

I'm on nixos, so the assumption that `git` will be in `/usr/bin` or `/bin` is incorrect.

I'm fine with this fix locally on my system, but I'm adding a note here so anyone in the same situation may find this.

> Just to note this fix won't be required in Nvim 0.10.

@lewis6991 does it mean that the fix should just be removed or set conditionally based on nvim version ?

**Comment by lewis6991** [comment]
I'm confused why you are only seeing this problem now. Do you get this on nvim nightly or nvim 0.11? If it's on 0.11 maybe we can just remove the env clearing.

**Comment by ibuki2003** [comment]
Hi, just adding some info here since I encountered the same issue (ENOENT) with Neovim nightly.

Recently, [neovim has been updated](https://github.com/neovim/neovim/commit/731e616a79d01e4797badbb4e18d167c51125151) to interpret `clear_env` as completely clear environment vars.
Since that update, system() no longer seems to be able to find executables from $PATH.

**Comment by BirdeeHub** [comment]
> Hi, just adding some info here since I encountered the same issue (ENOENT) with Neovim nightly.
> 
> Recently, [neovim has been updated](https://github.com/neovim/neovim/commit/731e616a79d01e4797badbb4e18d167c51125151) to interpret `clear_env` as completely clear environment vars. Since that update, system() no longer seems to be able to find executables from $PATH.

The update you linked to does not change the interpretation of clear_env to completely clear environment vars

The change you linked to fixes the env option when clear_env = true

when `clear_env = false`, the default, the env argument needs `env = { VARNAME = "VALUE" }`

the uv function it calls however needs a list of strings like `{ "VARNAME=VALUE" }`

So the function does some things to change the above.

however, prior to the linked change, when `clear_env = true`, it would completely skip that, and just return whatever you passed as env. This means you needed to change how you call vim.system to use `env = { "VARNAME=VALUE", "VAR2=VAL" }` yourself, but ONLY when `clear_env = true`.

When `clear_env = false` it matches the docs, and is set like `env = { VARNAME = "VALUE" }`

The fix linked fixes it so that changing the `clear_env` option no longer changes how `env` key works.

`clear_env` has always been intended to unset the existing environment? Im not sure what else it would be for?

`base_env()` is what returns the existing environment. If you have clear_env = true, it should not be added.

**Comment by lewis6991** [comment]
> clear_env has always been intended to unset the existing environment? Im not sure what else it would be for?

It's currently documented as:

```
                   • clear_env: (boolean) `env` defines the job environment
                     exactly, instead of merging current environment.
```

So to fully clear the environment, you needed `{env = {}, clear_env = true}`.

However `{env = nil, clear_env = true}` would pass env as `nil` (exactly as `env`).

So actually I think the new change did introduce a bug.

**Comment by BirdeeHub** [comment]
> > clear_env has always been intended to unset the existing environment? Im not sure what else it would be for?
> 
> It's currently documented as:
> 
> ```
>                    • clear_env: (boolean) `env` defines the job environment
>                      exactly, instead of merging current environment.
> ```
> 
> So to fully clear the environment, you needed `{env = {}, clear_env = true}`.
> 
> However `{env = nil, clear_env = true}` would pass env as `nil` (exactly as `env`).
> 
> So actually I think the new change did introduce a bug.

Hmmmm

It is within the letter of the setting.

I suppose you are right, since both technically could be interpreted to fit the description, so making it match the old behavior for that case is probably the best bet.

Personally, I would assume clear_env clears the env, but I suppose "defines the job environment exactly" doesnt exactly say that. I would assume nil would mean an empty environment other than what is passed by env but I also see how defines exactly would mean, that is the exact value which is passed to uv even when empty? For what it is worth, the type annotations didn't say the return value was optional.

So, a bit confusing, but, it seems to have caused some issues with people using clear_env when they don't actually want to clear the env so yeah thanks for figuring out what was going on.

**Comment by lewis6991** [comment]
Yeah exactly, the situation isn't ideal, but I lean towards not breaking old behaviour.

Using `{env=nil, clear_env=true}` also avoids creating the env table which could be costly, especially if it isn't really nedded.
